[project]
name = "pygamry"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "comtypes>=1.4.6",
    "matplotlib>=3.5.3",
    "numpy>=1.21.6",
    "pandas>=1.5.1",
    "ruff>=0.11.5",
    "scipy>=1.7.3",
]
